# tarmac.toml is Tarmac's configuration file.
# It tells Tarmac how to handle the assets in our project.

name = "01-basic-game"

# Most projects will define some 'inputs'.
# This tells Tarmac where to find assets that we'll use in our game.
[[inputs]]

# For a syntax overview of Tarmac's globs, see:
# https://docs.rs/globset/0.4.4/globset/#syntax
glob = "assets/**/*.png"

# Tells Tarmac to generate links to our assets in src/assets.lua.
codegen = true
codegen-path = "src/assets.lua"