-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	hello = function(dpiScale)
		if dpiScale >= 3 then
			return "rbxassetid://4967220945"
		elseif dpiScale >= 2 then
			return "rbxassetid://4967220902"
		else
			return "rbxassetid://4967166732"
		end
	end,
}