-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	assets = {
		hello = "rbxassetid://4967166732",
		["hello@2x"] = "rbxassetid://4967220902",
		["hello@3x"] = "rbxassetid://4967220945",
	},
}