-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	accept = function(dpiScale)
		if dpiScale >= 3 then
			return "rbxassetid://5094009091"
		elseif dpiScale >= 2 then
			return "rbxassetid://5094009034"
		else
			return "rbxassetid://5094008950"
		end
	end,
}