-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	Image = "rbxassetid://4643741386",
	ImageRectOffset = Vector2.new(129, 0),
	ImageRectSize = Vector2.new(128, 128),
}
