-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	Image = "rbxassetid://4603887944",
	ImageRectOffset = Vector2.new(0, 384),
	ImageRectSize = Vector2.new(128, 128),
}
