-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	Image = "rbxassetid://4642229227",
	ImageRectOffset = Vector2.new(128, 128),
	ImageRectSize = Vector2.new(128, 128),
}
