-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	a = {
		Image = "rbxassetid://4643741386",
		ImageRectOffset = Vector2.new(0, 0),
		ImageRectSize = Vector2.new(128, 128),
	},
	b = {
		Image = "rbxassetid://4643741386",
		ImageRectOffset = Vector2.new(129, 0),
		ImageRectSize = Vector2.new(128, 128),
	},
	c = {
		Image = "rbxassetid://4643741386",
		ImageRectOffset = Vector2.new(0, 129),
		ImageRectSize = Vector2.new(128, 128),
	},
	d = {
		Image = "rbxassetid://4643741386",
		ImageRectOffset = Vector2.new(258, 0),
		ImageRectSize = Vector2.new(128, 128),
	},
	e = {
		Image = "rbxassetid://4643741386",
		ImageRectOffset = Vector2.new(129, 129),
		ImageRectSize = Vector2.new(128, 128),
	},
}