-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	["pack-these"] = {
		["c.png"] = {
			Image = "rbxassetid://4643741386",
			ImageRectOffset = Vector2.new(0, 129),
			ImageRectSize = Vector2.new(128, 128),
		},
		["e.png"] = {
			Image = "rbxassetid://4643741386",
			ImageRectOffset = Vector2.new(129, 129),
			ImageRectSize = Vector2.new(128, 128),
		},
		["d.png"] = {
			Image = "rbxassetid://4643741386",
			ImageRectOffset = Vector2.new(258, 0),
			ImageRectSize = Vector2.new(128, 128),
		},
		["a.png"] = {
			Image = "rbxassetid://4643741386",
			ImageRectOffset = Vector2.new(0, 0),
			ImageRectSize = Vector2.new(128, 128),
		},
		["b.png"] = {
			Image = "rbxassetid://4643741386",
			ImageRectOffset = Vector2.new(129, 0),
			ImageRectSize = Vector2.new(128, 128),
		},
	},
}