name: Release

on:
  push:
    tags: ["*"]

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build release binary
      run: cargo build --verbose --locked --release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tarmac-win64
        path: target/release/tarmac.exe

  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

    - name: Build release binary
      run: |
        source $HOME/.cargo/env
        cargo build --verbose --locked --release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tarmac-macos
        path: target/release/tarmac

  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --locked --verbose --release
      env:
        OPENSSL_STATIC: 1

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tarmac-linux
        path: target/release/tarmac